backend:
  name: github
repo: stefimihai27/instalari-windows-mioveni
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "setari"
    label: "Administrare Site"
    files:
      - name: "home"
        label: "Pagina Principală"
        file: "index.html"
        fields:
          - label: "Titlu Principal (Hero)"
            name: "hero_title"
            widget: "string"
            default: "Instalări Windows ┃ Mioveni"

          - label: "Număr Telefon Contact"
            name: "phone"
            widget: "string"
            default: "07xx xxx xxx"

          - label: "Preț Pachet Basic"
            name: "price_basic"
            widget: "string"
            default: "100 RON"

          - label: "Preț Pachet Complet"
            name: "price_complet"
            widget: "string"

            default: "180 RON"
